### ISSUE TITLE
Formulas slightly different in french

### ISSUE THREAD

**Issue by natachabox** [MicrosoftDocs/powerapps-docs.fr-fr#4] opened 2018-10-30 10:34 UTC
I am using powerapps in French and you have to adapt the formulas because of the "chaining operation" as explained here :
https://powerusers.microsoft.com/t5/General-Discussion/Multiple-actions-in-a-formula/m-p/19692#M8618 
If(
    chkPhrases.Value = true;
    ClearCollect(
        phrasesCollect;
        Analytiquedetexte.KeyPhrases({text: tiTextToAnalyze.Text}).keyPhrases
    )
);;
If(
    chkLanguage.Value = true;
    ClearCollect(
        languageCollect;
        Analytiquedetexte.DetectLanguage(
            {
                numberOfLanguagesToDetect: 1;
                text: tiTextToAnalyze.Text
            }
        ).detectedLanguages.name
    )
);;
If(
    chkSentiments.Value = true;
    ClearCollect(
        sentimentCollect;
        Analytiquedetexte.DetectSentiment(
            {
                text: tiTextToAnalyze.Text;
                language: "en"
            }
        ).score
    )
)

For the sentiment score :
"The sentiment score is " & Round(First(sentimentCollect).Value; 3)*100 & "% positive."

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: e58cccc6-9234-ec33-b4b0-3303ebe282ef
* Version Independent ID: a556f95f-240d-206b-6dd0-c2fc47b1bf11
* Content: [Utiliser Cognitive Services dans PowerApps - PowerApps](https://docs.microsoft.com/fr-fr/powerapps/maker/canvas-apps/cognitive-services-api)
* Content Source: [powerapps-docs/maker/canvas-apps/cognitive-services-api.md](https://github.com/MicrosoftDocs/powerapps-docs.fr-fr/blob/live/powerapps-docs/maker/canvas-apps/cognitive-services-api.md)
* Service: **powerapps**
* GitHub Login: @AFTOwen
* Microsoft Alias: **anneta**

**Comment by CeciAc** [comment] 2018-10-30 16:01
Hello, @natachabox,
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment] 2018-10-30 16:03
Hi @Alisha-Acharya 
Can you please check this issue? The reported issue is for fr-FR and any other locale that uses comma as a decimal point.

Kind regards,
Microsoft DOCS International Team

**Comment by AFTOwen** [comment] 2018-10-30 16:31
CC: @gregli-msft

**Comment by CeciAc** [comment] 2018-11-12 19:03
Hi team, 
any update on this?

@AFTOwen @Alisha-Acharya @gregli-msft

**Comment by CeciAc** [comment] 2018-11-20 15:47
Hi team,
any update on this?

@AFTOwen @Alisha-Acharya @gregli-msft

**Comment by CeciAc** [comment] 2018-11-30 22:46
Hi team,
any update on this?

@AFTOwen @Alisha-Acharya @gregli-msft @DavidPrio

**Comment by AFTOwen** [comment] 2018-11-30 23:56
Hi, @CeciAc! The product team and Loc are working on a solution for this. It's complicated because most programming languages aren't localized the way that the formulas for PowerApps and Excel are. So it requires some invention and rethinking standard processes. We've been in discussion, but we have no ETA yet. Thanks for your patience!

cc: @gregli-msft @Alisha-Acharya

**Comment by v-maudel** [comment] 2019-02-08 19:53
Hi @AFTOwen , do you have any updates on this?

Regards.
@gregli-msft @Alisha-Acharya

**Comment by AFTOwen** [comment] 2019-02-08 22:58
@natachabox This topic has been updated with code so that the right version of the formula should appear based on locale. I believe that Loc is still working on how to support that code. Any thoughts, @Alisha-Acharya?

cc: @gregli-msft

**Comment by CeciAc** [comment] 2019-05-10 20:44
@Alisha-Acharya can you confirm if the fix was made so we can close this issue?

**Comment by jowilco** [comment] 2020-06-15 18:25
@CeciAc  I can confirm that this has been addressed.

**Closed** 2020-06-16 14:05 UTC
Labels: Linguistic Suggestion
